#!/usr/bin/env python3
from pathlib import Path
import math

out = Path("tube_particles.in")

lx = 1.2e-2
ly = 2.4e-3
tube_r = 4.5e-4
bead_spacing = 1.05e-4

centers = [
    (2.0e-3, 6.0e-3),
    (5.0e-3, 6.0e-3),
    (8.0e-3, 6.0e-3),
    (1.1e-2, 6.0e-3),
    (3.5e-3, 1.0e-2),
    (6.5e-3, 1.0e-2),
    (9.5e-3, 1.0e-2),
    (2.0e-3, 1.4e-2),
    (5.0e-3, 1.4e-2),
    (8.0e-3, 1.4e-2),
    (1.1e-2, 1.4e-2),
    (3.5e-3, 1.8e-2),
    (6.5e-3, 1.8e-2),
    (9.5e-3, 1.8e-2),
    (2.0e-3, 2.2e-2),
    (5.0e-3, 2.2e-2),
    (8.0e-3, 2.2e-2),
    (1.1e-2, 2.2e-2),
    (3.5e-3, 2.6e-2),
    (6.5e-3, 2.6e-2),
    (9.5e-3, 2.6e-2),
]

nphi = int(round(2.0 * math.pi * tube_r / bead_spacing))
ys = [bead_spacing * 0.55 + i * bead_spacing for i in range(int(ly / bead_spacing))]

lines = [
    "# Generated by make_tube_particles.py",
    "# Fixed type-2 beads approximating cylindrical heat-pipe tube surfaces.",
    f"# tube_radius_m = {tube_r:.8e}",
    f"# bead_spacing_m = {bead_spacing:.8e}",
    f"# n_tubes = {len(centers)}",
    f"# nphi = {nphi}",
]
count = 0
for itube, (xc, zc) in enumerate(centers, 1):
    for y in ys:
        for j in range(nphi):
            phi = 2.0 * math.pi * j / nphi
            x = xc + tube_r * math.cos(phi)
            z = zc + tube_r * math.sin(phi)
            if 0.0 < x < lx and 0.0 < y < ly:
                lines.append(f"create_atoms 2 single {x:.8e} {y:.8e} {z:.8e} units box")
                count += 1

lines.append(f'print "Created {count} fixed tube-wall beads"')
out.write_text("\n".join(lines) + "\n")
print(f"Wrote {out} with {count} tube-wall beads, {len(centers)} tubes, {nphi} azimuthal beads")
